services:
  thermoflow:
    image: ghcr.io/rafalantas/defro-dashboard:latest
    pull_policy: always
    container_name: defro-dashboard
    ports:
      - "5001:80"
    depends_on:
      - api
    restart: unless-stopped

  api:
    image: ghcr.io/rafalantas/defro-dashboard-api:latest
    pull_policy: always
    container_name: defro-dashboard-api
    environment:
      TECH_API_TOKEN: ${TECH_API_TOKEN:-}
      TECH_MODULE_ID: ${TECH_MODULE_ID:-}
    expose:
      - "8000"
    restart: unless-stopped
